# Generated by Django 3.2.7 on 2021-09-21 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='conent',
            new_name='content',
        ),
    ]
