# Generated by Django 3.2.7 on 2021-09-26 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20210925_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='tags',
            new_name='tag',
        ),
    ]
